version: '3.6'
services:
  postgres:
    image: postgres
    ports:
    - "${DB_PORT}:${DB_PORT}"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      SESSION_SECRET: ${SESSION_SECRET}
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-rc.1
    ports:
    - "${NIAMA_API_PORT}:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_USER}:${DB_PWD}@postgres:${DB_PORT}/${DB_NAME}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${NIAMA_API_SECRET}
      HASURA_GRAPHQL_AUTH_HOOK: ${NIAMA_AUTH_PROTOCOL}${NIAMA_AUTH_HOST}:${NIAMA_AUTH_PORT}/${NIAMA_AUTH_PATH}
volumes:
  db_data: