version: '3.6'
services:
  postgres:
    image: postgres
     ports:
    - "${DB_PORT}:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      SESSION_SECRET: ${SESSION_SECRET}
  graphql-engine:
    image: hasura/graphql-engine
    ports:
    - "${NIAMA_API_PORT}:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_USER}:${DB_PWD}@postgres:${DB_PORT}/${DB_NAME}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${NIAMA_API_ADMIN}
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "${NIAMA_API_JWT}"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${NIAMA_API_PUBLIC_ROLE}
volumes:
  db_data:
